Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -17,23 +17,6 @@ jobs:
           pip install -r requirements.txt
           python manage.py test taskManager
 
-  integration:
-    docker:
-      - image: python:3.6
-    steps:
-      - checkout
-      - run:
-          command: |
-            ls -la
-            echo "This is an integration step"
-            exit 1
-
-  prod:
-    docker:
-      - image: python:3.6
-    steps:
-      - run: echo "This is a deploy step."
-
   oast-snyk:
     docker:
       - image: node:alpine3.10
@@ -47,11 +30,30 @@ jobs:
             mv snyk /usr/local/bin/
             npm install
             snyk auth $SNYK_TOKEN
-            snyk test --json > snyk-results.json
+            snyk test --json > snyk-results.json || true
 
       - store_artifacts:
           path: snyk-results.json
           destination: snyk-artifact
+          when: always
+
+  integration:
+    docker:
+      - image: python:3.6
+    steps:
+      - checkout
+      - run:
+          command: |
+            echo "This is an integration step"
+            exit 1
+          when: on_fail         # Even if the job fails, continue to the next stages
+
+  prod:
+    docker:
+      - image: python:3.6
+    steps:
+      - checkout
+      - run: echo "This is a deploy step."
 
 workflows:
   version: 2
